sudo: required

branches:
  only:
  - dash

addons:
  ssh_konwn_hosts: $SERVER_IP
  apt:
    packages:
    - sshpass

services:
  - docker

script:
  - sshpass -e ssh $SERVER_USER@$SERVER_IP -o stricthostkeychecking=no 'cd ~/AI-Investment-Advisor && git pull origin dash && sh deploy.sh'
